# Generated by Django 5.1.1 on 2024-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('courts', models.CharField(max_length=255)),
            ],
        ),
    ]
