# Generated by Django 5.1.1 on 2024-09-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_scheduler', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
    ]
